<?php return array (
  'title' => '应用商店',
  'name' => 'Shop',
  'thumb' => 'http://test.hdcms.com/attachments/2019/03/11551535921.jpeg',
  'config' => '1',
  'domain' => '1',
  'wx_replies' => '1',
  'wx_cover' => '1',
  'menu_web' => false,
  'menu_mobile' => false,
  'subscribe' => '1',
  'processor' => false,
  'home_pc' => '1',
  'space_pc' => '1',
  'space_mobile' => '1',
);