<?php return array (
  'build' => 1552518733,
  'total' => 27,
  'logs' => 
  array (
    0 => '更新跳转逻辑',
    1 => '修复模块更新异常',
    2 => '优化模块更新',
    3 => '修复模块会员中心菜单异常',
    4 => '修复管理员头像错误',
    5 => '修改用户迁移文件',
    6 => '用户多站点分组',
    7 => '用户积分处理',
    8 => '.gitignore',
    9 => '优化模块webpack.mix.js',
    10 => '修复模块截图上传异常',
  ),
  'files' => 
  array (
    '.gitignore' => 'M',
    'app/Console/Commands/updateHouDunRen.php' => 'M',
    'app/Http/Controllers/Site/UploaderController.php' => 'M',
    'app/Http/Controllers/System/UploaderController.php' => 'M',
    'app/Http/Controllers/Update/ModuleController.php' => 'M',
    'app/Http/Controllers/Update/SystemController.php' => 'M',
    'app/Http/Middleware/InstallMiddleware.php' => 'M',
    'app/Models/Favour.php' => 'M',
    'app/Providers/AppServiceProvider.php' => 'M',
    'app/Repositories/ModuleRepository.php' => 'M',
    'app/User.php' => 'M',
    'bootstrap/app.php' => 'M',
    'database/migrations/2014_10_12_000000_create_users_table.php' => 'M',
    'database/seeds/UserSeeder.php' => 'M',
    'public/mix-manifest.json' => 'M',
    'public/modules/edu/css/app.css' => 'M',
    'public/modules/edu/images/.gitkeep' => 'M',
    'public/modules/edu/js/app.js' => 'M',
    'public/modules/shop/css/app.css' => 'M',
    'public/modules/shop/images/shop_Jietu20190303-110612.jpg' => 'M',
    'public/modules/shop/images/shop_home_banner.png' => 'M',
    'public/modules/shop/images/shop_kuaisu.png' => 'M',
    'public/modules/shop/js/app.js' => 'M',
    'resources/views/site/site/show.blade.php' => 'M',
    'resources/views/system/module/_form.blade.php' => 'M',
    'resources/views/system/user/index.blade.php' => 'M',
    'resources/views/update/module/update.blade.php' => 'M',
  ),
);