<?php return array (
  'build' => 1552032482,
  'total' => 27,
  'logs' => 
  array (
    0 => '粉丝关注点赞',
  ),
  'files' => 
  array (
    'app/Http/Controllers/InstallController.php' => 'M',
    'app/Http/Controllers/Member/NotifyController.php' => 'M',
    'app/Http/Middleware/SystemMiddleware.php' => 'M',
    'app/Http/Requests/ChatRequest.php' => 'M',
    'app/Http/Requests/GroupRequest.php' => 'M',
    'app/Http/Requests/ModuleRequest.php' => 'M',
    'app/Http/Requests/PackageRequest.php' => 'M',
    'app/Policies/GroupPolicy.php' => 'M',
    'app/Policies/PackagePolicy.php' => 'M',
    'app/Policies/SitePolicy.php' => 'M',
    'app/Policies/UserPolicy.php' => 'M',
    'app/Policies/WeChatPolicy.php' => 'M',
    'app/Providers/AuthServiceProvider.php' => 'M',
    'app/Repositories/SiteRepository.php' => 'M',
    'app/User.php' => 'M',
    'app/helper.php' => 'M',
    'database/migrations/2019_02_17_135919_module_package.php' => 'M',
    'database/migrations/2019_03_06_212803_create_followers_table.php' => 'M',
    'database/migrations/2019_03_06_234437_create_favours_table.php' => 'M',
    'database/migrations/2019_03_07_022214_create_favorites_table.php' => 'M',
    'database/migrations/2019_03_07_201628_create_activity_log_table.php' => 'M',
    'resources/views/layouts/hdjs.blade.php' => 'M',
    'resources/views/layouts/site.blade.php' => 'M',
    'resources/views/layouts/system.blade.php' => 'M',
    'resources/views/site/user/index.blade.php' => 'M',
    'routes/web.php' => 'M',
    'routes/web/member.php' => 'M',
  ),
);