<?php return array (
  'build' => 1555052028,
  'total' => 26,
  'logs' => 
  array (
    0 => '添加处理自定义字段的FieldServer服务',
    1 => '模型自动构建数据仓库',
    2 => '模型自动构建数据仓库',
    3 => '添加模型动态生成功能',
    4 => '添加xss处理库',
    5 => '添加xss处理库',
  ),
  'files' => 
  array (
    '.gitignore' => 'M',
    'app/Http/Controllers/Develop/MigrateController.php' => 'M',
    'app/Http/Controllers/Develop/ModelController.php' => 'M',
    'app/Servers/FieldServer.php' => 'M',
    'app/Servers/Model/Controller.php' => 'M',
    'app/Servers/Model/Migration.php' => 'M',
    'app/Servers/Model/Model.php' => 'M',
    'app/Servers/Model/Repository.php' => 'M',
    'app/Servers/Model/Tpls/controller.tpl' => 'M',
    'app/Servers/Model/Tpls/migration.tpl' => 'M',
    'app/Servers/Model/Tpls/model.tpl' => 'M',
    'app/Servers/Model/Tpls/repository.tpl' => 'M',
    'app/Servers/ModelServer.php' => 'M',
    'config/purifier.php' => 'M',
    'public/mix-manifest.json' => 'M',
    'resources/views/develop/model/_form.blade.php' => 'M',
    'resources/views/develop/model/_tab.blade.php' => 'M',
    'resources/views/develop/model/create.blade.php' => 'M',
    'resources/views/servers/field/input.blade.php' => 'M',
    'resources/views/servers/field/ueditor.blade.php' => 'M',
    'resources/views/system/module/index.blade.php' => 'M',
    'routes/web.php' => 'M',
    'routes/web/develop.php' => 'M',
    'routes/web/system.php' => 'M',
    'vendor/composer/autoload_classmap.php' => 'M',
    'vendor/composer/autoload_static.php' => 'M',
  ),
);