<?php return array (
  'build' => 1557064511,
  'total' => 46,
  'logs' => 
  array (
    0 => 'UI优化',
    1 => '优化验证码处理机制',
    2 => '优化自定义模块字段',
    3 => '优化模型',
    4 => '添加markdown自定义字段支持',
    5 => '优化模型自动构建',
    6 => '优化标签过滤机制',
  ),
  'files' => 
  array (
    'app/Http/Controllers/Develop/ModelController.php' => 'M',
    'app/Http/Controllers/Member/FindPasswordController.php' => 'M',
    'app/Http/Controllers/Member/NotifyController.php' => 'M',
    'app/Http/Controllers/Member/RegisterController.php' => 'M',
    'app/Http/Controllers/Module/DomainController.php' => 'M',
    'app/Http/Controllers/Update/SystemController.php' => 'M',
    'app/Models/Validation.php' => 'M',
    'app/Servers/FieldServer.php' => 'M',
    'app/Servers/Model/Controller.php' => 'M',
    'app/Servers/Model/Migration.php' => 'M',
    'app/Servers/Model/Model.php' => 'M',
    'app/Servers/Model/Repository.php' => 'M',
    'app/Servers/Model/Vars.php' => 'M',
    'app/Servers/Model/View.php' => 'M',
    'app/Servers/Model/app/controller.tpl' => 'M',
    'app/Servers/Model/views/_form.blade.php' => 'M',
    'app/Servers/Model/views/_tab.blade.php' => 'M',
    'app/Servers/Model/views/create.blade.php' => 'M',
    'app/Servers/Model/views/edit.blade.php' => 'M',
    'app/Servers/Model/views/index.blade.php' => 'M',
    'app/Servers/ModelServer.php' => 'M',
    'app/Servers/NotifyServer.php' => 'M',
    'app/helper.php' => 'M',
    'config/purifier.php' => 'M',
    'database/migrations/2019_05_05_203659_create_validations_table.php' => 'M',
    'hdcms.code-workspace' => 'M',
    'public/index.php' => 'M',
    'public/js/util.js' => 'M',
    'resources/views/develop/model/_form.blade.php' => 'M',
    'resources/views/develop/model/index.blade.php' => 'M',
    'resources/views/member/findPassword/index.blade.php' => 'M',
    'resources/views/member/login/login.blade.php' => 'M',
    'resources/views/member/register/index.blade.php' => 'M',
    'resources/views/servers/field/checkbox.blade.php' => 'M',
    'resources/views/servers/field/image.blade.php' => 'M',
    'resources/views/servers/field/input.blade.php' => 'M',
    'resources/views/servers/field/markdown.blade.php' => 'M',
    'resources/views/servers/field/radio.blade.php' => 'M',
    'resources/views/servers/field/show/checkbox.blade.php' => 'M',
    'resources/views/servers/field/show/image.blade.php' => 'M',
    'resources/views/servers/field/show/radio.blade.php' => 'M',
    'resources/views/servers/field/textarea.blade.php' => 'M',
    'resources/views/servers/field/ueditor.blade.php' => 'M',
    'routes/web.php' => 'M',
    'vendor/composer/autoload_classmap.php' => 'M',
    'vendor/composer/autoload_static.php' => 'M',
  ),
);